### PR TITLE
refractor: try to port it to jsr

### PR DESCRIPTION
**Pull request by Decodetalkers**

### CODE REVIEW

**Comment by Decodetalkers** [comment]
but seems cannot use bin to run target.. because I use lib from npm now

**Comment by bpevs** [comment]
Thanks for your interest and help!  I pulled your existing commits into https://github.com/bpevs/bext/tree/jsr. With some minor edits, I already ran `deno publish --dry-run`, and it looks happy. Will probably move the code back from that branch into this PR + merge after finishing the tasks below:

Over the next couple days, i'll
- [x] Validate the (sorely needed) dependency updates
- [ ] Add comments that play well with jsr doc autogen
- [x] Confirm example works locally
- [ ] Move [Favioli](https://github.com/bpevs/favioli) code to use jsr update, to validate that everything is gucci e2e
- ❌  ~Maybe use [workspaces](https://docs.deno.com/runtime/manual/basics/workspaces/) if it makes it easier to use current version of `bext` in the local examples~
  - In order to avoid polluting compilerOptions, will not use workspaces, [as only one can be used per-workspace](https://docs.deno.com/runtime/manual/basics/workspaces/)

**Comment by Decodetalkers** [comment]
https://github.com/bpevs/bext/blob/jsr/source%2Fmain.ts#L90-L97

This part is wrong.. esbuild-deno-loader has already handled the import part in deno.json, so we do not need to handle it again. We just need to pass the position of deno.json to it, and when importmap.json does not exist, pass undefined to it

I handle it in https://github.com/bpevs/bext/commit/af37cc7ff0a20ffa8297641b1cbf94c1f7ec3732

And it seems that esbuild-deno-loader itself has already handled the logic from string to path.

https://github.com/lucacasonato/esbuild_deno_loader/blob/main/src%2Fplugin_deno_resolver.ts#L81-L87

The logic of how esbuild-deno-loader handles the import part of deno.json is here

**Comment by bpevs** [comment]
Was that code working for you?  I wasn't able to get that change to work with the example preact app; esbuild wasn't seeing the imports from deno.json. I don't mind the update, but I just reverted that change for now, since it was working before; probably would prefer to handle in separate change just to keep it separate in my brain space. Esp for file resolution, since this is a non-standard use of esbuild, because this script is run out-of-context from the file location.

For reference; what I am testing is:
- root: `deno task test`
- examples/preact: `deno task test`
- examples/preact: `deno task build` > load dist in browser

Preferably would like deno.json `compilerOptions` and `imports` to be respected, but it seems like it's a little more trouble than I expected, so I'm just jumping into jsr-specific changes first.

fwiw, initial pre-release looks like it works: https://jsr.io/@bpev/bext@1.2.0-beta.1


edit: I think it looks like your code will compile the target if I keep the `file://` in importMapURL, but if `configPath` is provided, import_map.json will always be ignored in favor of even an empty deno.json `imports` block? In any case, going to bed for today.

**Comment by Decodetalkers** [comment]
> Was that code working for you? I wasn't able to get that change to work with the example preact app; esbuild wasn't seeing the imports from deno.json. I don't mind the update, but I just reverted that change for now, since it was working before; probably would prefer to handle in separate change just to keep it separate in my brain space. Esp for file resolution, since this is a non-standard use of esbuild, because this script is run out-of-context from the file location.
> 
> For reference; what I am testing is:
> 
>     * root: `deno task test`
> 
>     * examples/preact: `deno task test`
> 
>     * examples/preact: `deno task build` > load dist in browser
> 
> 
> Preferably would like deno.json `compilerOptions` and `imports` to be respected, but it seems like it's a little more trouble than I expected, so I'm just jumping into jsr-specific changes first.
> 
> fwiw, initial pre-release looks like it works: https://jsr.io/@bpev/bext@1.2.0-beta.1
> 
> edit: I think it looks like your code will compile the target if I keep the `file://` in importMapURL, but if `configPath` is provided, import_map.json will always be ignored in favor of even an empty deno.json `imports` block? In any case, going to bed for today.

I think it is works.. and the logic should works. I have already read that code.. it should have handled that part... Thanks for your hard work!

**Pull request merged**
